// AUTO-GENERATED by build.rs. Do not edit manually.
pub mod day01;
pub mod day02;
pub mod day03;
pub mod day04;

pub fn run_day(day: u32, part: u8, use_example: bool) -> Option<String> {
    match (day, part) {
        (1, 1) => Some(day01::part1(use_example)),
        (1, 2) => Some(day01::part2(use_example)),
        (2, 1) => Some(day02::part1(use_example)),
        (2, 2) => Some(day02::part2(use_example)),
        (3, 1) => Some(day03::part1(use_example)),
        (3, 2) => Some(day03::part2(use_example)),
        (4, 1) => Some(day04::part1(use_example)),
        (4, 2) => Some(day04::part2(use_example)),
        _ => None,
    }
}
